image: python:3.11

pipelines:
  default:
    - step:
        name: "Lint"
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install flake8
          - flake8 .
    - step:
        name: "Unit Tests"
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python -m unittest discover -s tests -p '*_tests.py'